<a href="https://colab.research.google.com/github/trilgar/IAD2023/blob/main/%D0%97%D0%B0%D1%80%D0%B8%D1%86%D1%8C%D0%BA%D0%B8%D0%B9_CP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<center><font size="6"><b>Комп'ютерний практикум 2.

Python для математичних обчислень</b></font></center>

>Мова програмування Python підтримує сторонні бібліотеки та фреймворки. Необхідні пакети можна знайти в центральному репозиторії Python — PyPI (Python Package Index — каталог пакетів Python). Існує спеціальний інструмент PIP для Python, який прискорює та спрощує цей процес.Це утиліта командного рядка, яка дозволяє встановлювати, перевстановлювати та деінсталювати PyPI пакеты простою командою `pip`.

```
$ pip install numpy
$ pip install numpy >= 1.17 # specify the version needed
```

>Для того, щоб додати модуль в ваш робочий простір, ви можете викликати функцію командою `import`.

```python
# варіант 1
import numpy as np # імпорт пакету зі скороченою назвою
# варіант 2
from numpy import linalg # імпорт лише модулю `linalg` 
# варіант 3
from numpy import * # імпорт всих модулів пакету `numpy`
```

* Використовуючи варіант #1 ви отримуєте доступ до всіх модулів пакету `numpy` шляхом виклику команди `np.{function name}` (наприклад, `np.abs()`). 
* Використовуючи варіант #2 ви отримуєте доступ до модуля `linalg`  (наприклад, `linalg.eigvals()`). 

* Використовуючи варіант #3 ви отримуєте доступ до всіх модулів пакету `numpy` напряму через іх назву (наприклад `empty()`). Даний метод не рекомендується використовувати через дублювання назв модулів в різних пакетах

> __NumPy__ — це бібліотека Python, яка забезпечує підтримку великих багатомірних масивів та матриць значною бібліотекою високорівневих та швидкісних математичних функцій для операцій з цими масивами.
<center><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIPFCW7PLmNQCYHAP_e8tOsaQ1FGhOKpGR4ZvvTcXp0wO5MA6yiBzk0iXBGPBfEfUPlec&usqp=CAU" width="200"></center>

[NumPy документація](https://numpy.org/doc/)


In [2]:
#імпортуємо бібліотеку NumPy
import numpy as np

### Створення матриць

Найпростіший спосіб — за допомогою функції __`numpy.array(list, dtype=None, ...)`__.

В якості першого аргументу передається інтегруючий об'єкт, елементами якого є інші інтегруючі об'єкти однакової довжини, які містять однотипні дані.

Другий аргумент є опціональним та визначає тип даних матриці. Його можна не задавати, тоді тип даних буде визначатись з типу елементів першого аргументу.

### <i> Наприклад </i>

In [3]:
#цілочисельна матриця
a = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
print ("Матриця:\n", a)

Матриця:
 [[1 2 3]
 [2 5 6]
 [6 7 4]]


Інший спосіб створення матриць — за допомогою вбудованих функцій __`numpy.eye(N, M=None, ...)`__, __`numpy.zeros(shape, ...)`__, __`numpy.ones(shape, ...)`__.

Перша функція створює вбудовану матрицю розмірності  $N \times M$; якщо $M$ не задано, то $M = N$. 

Друга та третя функції створюють матриці, які складаються цілком з нулів та одиниць відповідно. В якості першого аргументу задається розмірність масиву  — кортеж цілих чисел. В двовимірному випадку це набір з двох чисел: кількість рядків та стовпців матриці.

### <i> Наприклад </i>

In [4]:
b = np.eye(5)
print ("Одинична матриця:\n", b)

Одинична матриця:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
c = np.ones((7, 5))
print ("Матриця з одиниць:\n", c)

Матриця з одиниць:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Третій спосіб — за допомогою функції __`numpy.arange([start, ]stop, [step, ], ...)`__, яка створює одновимірний масив з проміжку __`[start, stop)`__ с заданим кроком __`step`__, та _методом_ __`array.reshape(shape)`__. 

Параметр __`shape`__, задає розмірність матриці (кортеж чисел).

### <i> Наприклад </i>

In [6]:
v = np.arange(0, 24, 2)
print ("Вектор:\n", v)

Вектор:
 [ 0  2  4  6  8 10 12 14 16 18 20 22]


In [7]:
#перетворення вектора v в матрицю за допомогою команди `reshape`
d = v.reshape((3, 4))
print ("Матриця:\n", d)

Матриця:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


>*Більш детально про масиви `NumPy`, 
див. [документацію](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).*

### Індексування

Для отримання елементів матриці можна використовувати декілька способів.

Елемент на перетині рядка __`i`__ та стовпця __`j`__ можна отримати за допомогою команди __`array[i, j]`__. 

___Увага:___ рядки та стовпці нумеруються з нуля!

In [8]:
print ("Елемент d32 матриці:", d[2, 1])

Елемент d32 матриці: 18


З матриці можна отримати рядки та стовпці:
 __`array[i, :]`__ або __`array[:, j]`__ відповідно:

In [9]:
print ("Другий рядок матриці d:\n", d[1, :])
print ("Четвертий стовпчик матриці d:\n", d[:, 3])

Другий рядок матриці d:
 [ 8 10 12 14]
Четвертий стовпчик матриці d:
 [ 6 14 22]


Ще один спосіб отримання елементів матриці —  __`array[list1, list2]`__, де __`list1`__, __`list2`__ — деякі списки цілих чисел. При такій адресації одночасно переглядаються обидва списки та повертаються матриці з відповідними координатами:

In [10]:
print ("Елементи матриці d з координатами (1, 2) та (0, 3):\n", d[[1, 0], [2, 3]])

Елементи матриці d з координатами (1, 2) та (0, 3):
 [12  6]


>*Більш детально про різні способи індексації в масивах
див. [документацію](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).*

### Вектори

In [11]:
# задамо масиви a та b
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])


In [12]:
print ("Вектор:\n", a)
print ("Розмірність вектору а:\n", a.shape)
print ("Двовиміриний масив:\n", b)
print ("Розмірність масиву b:\n", b.shape)

Вектор:
 [1 2 3]
Розмірність вектору а:
 (3,)
Двовиміриний масив:
 [[1]
 [2]
 [3]]
Розмірність масиву b:
 (3, 1)


__Зверніть увагу:__ _вектор_ (одновимірний масив) та _вектор-стовпчик_ або _вектор-рядок_ (двовимірний масиви) є різними об'єктами в `NumPy`. У випадку одновимірного масиву кортеж __`shape`__ складається з одного числа та має вигляд __`(n,)`__, де __`n`__ — довжина вектора. У випадку двовимірних векторів в __`shape`__ присутня ще одна розмірність, рівна одиниці. 

In [13]:
#транспонуємо вектори
a = a.T
b = b.T

In [14]:
print ("Вектор не змінився при транспонуванні:\n", a)
print ("Розмірність вектору а не змінилася:\n", a.shape)
print ("Транспонований двовиміриний масив:\n", b)
print ("Розмірність транспонованого масиву b:\n", b.shape)

Вектор не змінився при транспонуванні:
 [1 2 3]
Розмірність вектору а не змінилася:
 (3,)
Транспонований двовиміриний масив:
 [[1 2 3]]
Розмірність транспонованого масиву b:
 (1, 3)


### Множення матриць та векторів

__ТЕОРІЯ__ 

Операція __множення__ визначена для двох узгоджених матриць, коли кількість стовпців першої рівна кількості рядків другої. 

Нехай матриці $A$ та $B$ такі, що $A \in \mathbb{R}^{n \times k}$ та $B \in \mathbb{R}^{k \times m}$. __Добутком__ матриць $A$ та $B$ є матриця $C$, така що $c_{ij} = \sum_{r=1}^{k} a_{ir}b_{rj}$, де $c_{ij}$ — елемент матриці $C$, який стоїть на перетині $i$-го рядка та $j$-го стовпця.

В `NumPy` добуток матриць обчислюється за допомогою _функції_ __`numpy.dot(a, b, ...)`__ або за допомогою _методу_ __`array1.dot(array2)`__, де __`array1`__ та __`array2`__ — матриці, що перемножаються.

In [15]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
r1 = np.dot(a, b)
r2 = a.dot(b)

In [16]:
print ("Матриця A:\n", a)
print ("Матриця B:\n", b)
print ("Результат множення функцією:\n", r1)
print ("Результат множення методом:\n", r2)

Матриця A:
 [[1 0]
 [0 1]]
Матриця B:
 [[4 1]
 [2 2]]
Результат множення функцією:
 [[4 1]
 [2 2]]
Результат множення методом:
 [[4 1]
 [2 2]]


> __Зверніть увагу:__ операція __`*`__ проводить покоординатне множення, а не матричне!

In [17]:
r = a * b

In [18]:
print ("Матриця A:\n", a)
print ("Матриця B:\n", b)
print ("Результат покоординатного множення:\n", r)

Матриця A:
 [[1 0]
 [0 1]]
Матриця B:
 [[4 1]
 [2 2]]
Результат покоординатного множення:
 [[4 0]
 [0 2]]


>*Більш детально про множення матриць в `NumPy`
див. [документацію](http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).*

### Транспонування матриць

__ТЕОРІЯ__ 

__Транспонованою матрицею__ $A^{T}$ називається матриця, утворена з вихіднох матриці $A$ шляхом заміни рядків на стовпці. Формально: елементи матриці $A^{T}$ визначаються як $a^{T}_{ij} = a_{ji}$, де $a^{T}_{ij}$ — елемент матриці $A^{T}$, який стоїть на перетині $i$-го рядка та $j$-го стовпця.

В `NumPy` транспонована матриця обчислюється за допомогою функціії __`numpy.transpose()`__ обо _методу_ __`array.T`__, де __`array`__ — вихідний масив.

In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.transpose(a)
c = a.T

In [20]:
print ("Вихідна матриця:\n", a)
print ("Транспонування функцією:\n", b)
print ("Транспонування методом:\n",  c)

Вихідна матриця:
 [[1 2]
 [3 4]]
Транспонування функцією:
 [[1 3]
 [2 4]]
Транспонування методом:
 [[1 3]
 [2 4]]


>*Більш детально про [numpy.transpose()](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.transpose.html) и 
[array.T](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.T.html) в `NumPy`.*

### Визначник матриці

__ТЕОРІЯ__ 

Для квадратних матриць існує об'єкт (числова характеристика) __визначник__.

Нехай $A$ — квадратна матриця. __Визначником__ (або __детермінантом__) матриці $A \in \mathbb{R}^{n \times n}$ називається число 

$$\det A = \sum_{\alpha_{1}, \alpha_{2}, \dots, \alpha_{n}} (-1)^{N(\alpha_{1}, \alpha_{2}, \dots, \alpha_{n})} \cdot a_{\alpha_{1} 1} \cdot \cdot \cdot a_{\alpha_{n} n},
$$
де $\alpha_{1}, \alpha_{2}, \dots, \alpha_{n}$ — перестановка чисел від $1$ до $n$, $N(\alpha_{1}, \alpha_{2}, \dots, \alpha_{n})$ — число інверсій в перестановці, сума ведеться по всим можливим перестановкам довжини $n$.

>Обчислення визначника матриці в `NumPy` відбувається за допомогою функції __`numpy.linalg.det(a)`__, де __`a`__ — вихідна матриця.

In [21]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
det = np.linalg.det(a)

In [22]:
print ("Матриця:\n", a)
print ("Визначник:\n", det)

Матриця:
 [[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
Визначник:
 -1.0


### Ранг матриці

__ТЕОРІЯ__

__Рангом матриці__ $A$  називається максимальна кількість лінійно незалежних рядків (стовпців) матриці.

В `NumPy` ранг матриці обчислюється за допомогою функції __`numpy.linalg.matrix_rank(M, tol=None)`__, де __`M`__ — матриця, __`tol`__ — параметр, який відповідає за деяку точність обчислень. В простому випадку його можна не задавати, функція підбирає його автоматично.

In [23]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 2]])
r = np.linalg.matrix_rank(a)

In [24]:
print ("Матриця:\n", a)
print ("Ранг матриці:", r)

Матриця:
 [[1 2 3]
 [1 1 1]
 [2 2 2]]
Ранг матриці: 2


> За допомогою рангу перевіряється лінійна залежність/незалежність системи векторів: для лінійної незалежності кількість векторів повинна співпадати з рангом системи з цих векторів.


In [25]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])
c = np.array([2, 3, 5])
m = np.array([a, b, c])

In [26]:
print (np.linalg.matrix_rank(m) == m.shape[0])

True


### Системи лінійних рівнянь

__ТЕОРІЯ__ 

__Системою лінійних алгебраїчних рівнянь (СЛАР)__ називається система виду $Ax = b$, де $A \in \mathbb{R}^{n \times m}, x \in \mathbb{R}^{m \times 1}, b \in \mathbb{R}^{n \times 1}$. У випадку квадратної невиродженої матриці $A$ розв'язок системи єдиний.

В `NumPy` розв'язок СЛАР можна знайти за допомогою функції __`numpy.linalg.solve(a, b)`__, де перший аргумент — матриця $A$, другий — стовпчик $b$.

In [27]:
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(a, b)

In [28]:
print ("Матриця A:\n", a)
print ("Вектор b:\n", b)
print ("Розв'язок системи:\n", x)

Матриця A:
 [[3 1]
 [1 2]]
Вектор b:
 [9 8]
Розв'язок системи:
 [2. 3.]


In [29]:
#Впевнимося, що вектор x дійсно є розв'язком вихідної системи:
print (a.dot(x))

[9. 8.]


> Якщо розв'язок системи не існує, то шукають такий вектор $x$, який мінімізує вираз $\left\Vert Ax - b\right\Vert^{2}$ — так ми наблизимо  вираз $Ax$ до $b$.

В `NumPy` такий псевдорозв'язок можна шукати за допомогою функції __`numpy.linalg.lstsq(a, b, ...)`__, де перші два аргументи такі ж, як і для функції __`numpy.linalg.solve()`__. 


In [30]:
a = np.array([[0, 1], [1, 1], [2, 1], [3, 1]])
b = np.array([-1, 0.2, 0.9, 2.1])
x, res, r, s = np.linalg.lstsq(a, b)

<ipython-input-30-32ee29679dc4>:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, res, r, s = np.linalg.lstsq(a, b)


In [31]:
print ("Матриця A:\n", a)
print ("Вектор b:\n", b)
print ("Псевдорозв'язок системи:\n", x)

Матриця A:
 [[0 1]
 [1 1]
 [2 1]
 [3 1]]
Вектор b:
 [-1.   0.2  0.9  2.1]
Псевдорозв'язок системи:
 [ 1.   -0.95]


### Обернена матриця

__ТЕОРІЯ__  

Нехай $A$ — квадратна невироджена матриця. Матриця $A^{-1}$ називається __оберненою матрицею__ до $A$, якщо 

$$AA^{-1} = A^{-1}A = I,
$$ 

де $I$ — одинична матриця такої ж розмірності як і $A$.

В `NumPy` обернені матриці обчислюються за допомогою функції __`numpy.linalg.inv(a)`__, де __`a`__ — вихідна матриця.

In [32]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
b = np.linalg.inv(a)

In [33]:
print ("Матриця A:\n", a)
print ("Обернена матриця до A:\n", b)
print ("перевірка: добуток матриці А на обернену повинен дорівнювати одиничній матриці:\n", a.dot(b))

Матриця A:
 [[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
Обернена матриця до A:
 [[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]
перевірка: добуток матриці А на обернену повинен дорівнювати одиничній матриці:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Власні числа та власні вектори матриці

__ТЕОРІЯ__ 

Нехай $A$ — квадратна матриця та $A \in \mathbb{R}^{n \times n}$. __Власним вектором__ матриці $A$ називається такий ненульовий вектор $x \in \mathbb{R}^{n}$, що для деякого $\lambda \in \mathbb{R}$ виконується рівність $Ax = \lambda x$. При цьому $\lambda$ називається __власним числом__ матриці $A$.

В `NumPy` власні числа та власні вектори обчислюються за допомогою функції __`numpy.linalg.eig(a)`__, де __`a`__ — вихідна матриця. Як результат функція видає одновимірний масив __`w`__ власних чисел та двовимірний масив __`v`__, в якому по стовпцям записані власні вектори, так що вектор __`v[:, i]`__ відповідає власному числу __`w[i]`__.

In [34]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

In [35]:
print ("Матриця A:\n", a)
print ("Власні числа:\n", w)
print ("Власні вектори:\n", v)

Матриця A:
 [[-1 -6]
 [ 2  6]]
Власні числа:
 [2. 3.]
Власні вектори:
 [[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


### Комплексні числа в Python

__ТЕОРІЯ__

__Комплексними числами__ називаються числа виду $x + iy$, де $x$ та $y$ — дійсні числа, а $i$ — уявна комплексна одиниця (величина, для якої виконується рівність $i^{2} = -1$). Множина всих комплексних чисел позначається $\mathbb{C}$ 

> В Python  комплескні числа можно задати наступним чином (__j__ позначає уявну одиницю):

In [36]:
a = 3 + 2j
b = 1j

In [37]:
print ("Комплексне число a:\n", a)
print ("Комплексне число b:\n", b)

Комплексне число a:
 (3+2j)
Комплексне число b:
 1j


> З комплексними числами в Python можна проводити базові арифметичні операції, як і з дійсними числами:

In [38]:
c = a * a
d = a / (4 - 5j)

print ("Комплексне число c:\n", c)
print ("Комплексне число d:\n", d)

Комплексне число c:
 (5+12j)
Комплексне число d:
 (0.0487804878048781+0.5609756097560976j)


>*Більш детально про наведені та інші функції модуля __`numpy.linalg`__ див. [документацію](http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#linear-algebra-numpy-linalg).*

## SymPy

> `SymPy` це бібліотека символьної математики в Python. 

<center><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Sympy_logo.svg/1200px-Sympy_logo.svg.png" width="150"></center>

Може застосовуватись в таких розділах як:

* Поліноми
* Диференційне та інтегральне числення
* Розв'язок СЛР
* Комбінаторика
* Дискретна математика
* Матриці
* Геометрія
* Фізика
* Статистика
* Криптографія

[SymPy документація](https://docs.sympy.org/latest/index.html)


In [39]:
#імпортуємо бібліотеку SymPy
import sympy as sym

In [40]:
# застосуємо команду Symbol до змінних
x = sym.Symbol('x')
y = sym.Symbol('y')
print(x)
print(type(x))

x
<class 'sympy.core.symbol.Symbol'>


### Алгебраїчні операції

> можна обирати формат виводу результату на екран за допомогою модулю `init_printing`

In [41]:
from sympy.interactive.printing import init_printing
init_printing(pretty_print=True, use_latex=True)

> розклад алгебраїчних виразів за допомогою команди `expand`

In [42]:
sym.expand((x + y) ** 2)

>різні версії виводу на екран результату розкладу виразу
$$x^{2} + 2 x y + y^{2}$$

In [43]:
init_printing(pretty_print=False, use_latex=False)
sym.expand((x + y) ** 2)

x**2 + 2*x*y + y**2

In [44]:
init_printing(pretty_print=False, use_latex=True)
sym.expand((x + y) ** 2)

> спростити алгебраїчні операції можна за допомогою команди`simplify`

In [45]:
sym.simplify((x + x * y) / x)

In [46]:
sym.simplify(sym.cos(x)/sym.sin(x))

### (Основи математичного аналізу) Calculus

>__Границі (Limits)__ в SymPy можна обчислювати за допомогою функції `limit(function, variable, point)`

Якщо треба обчислити limit функції $f(x)$ при $x \rightarrow 0$, тоді запишемо `limit(f, x, 0)`:

In [47]:
sym.limit(sym.sin(x)/x, x, 0)

In [48]:
# для позначення нескінченості використовують `oo`
sym.limit(1/x, x, sym.oo)

> __Диференціювати__ в SymPy можна за допомогою команди `diff(func, var)`.

In [49]:
sym.diff(x**2 + x + 1, x)

In [50]:
sym.diff(sym.sin(2 * x**2), x)

In [51]:
sym.diff(sym.sin(x + 2*y), x)

> __Похідну старшого порядку__ знаходять використовуючу ту саму функцію, але вводять третій аргумент, де вказується порядок похідної `diff(func, var, n)`.

In [52]:
print(sym.diff(x**2 + x + 1, x, 1)) # перша похідна
print(sym.diff(x**2 + x + 1, x, 2)) # друга похідна
print(sym.diff(x**2 + x + 1, x, 3)) # третя похідна

2*x + 1
2
0


> __Інтегрувати__ в SymPy можна використовуючи функцію `integrate(func,var)`

In [53]:
sym.integrate(x**2 + x + 1, x)

> Для знаходження __визначеного інтеграла__ вказується не тільки змінна інтегрування в якості другого аргументу, а кортеж зі змінної та меж інтегрування `integrate(func,(var, low_bord, up_bord)`

In [54]:
sym.integrate(x**2 + x + 1, (x, -1, 1))

### Матриці 

In [55]:
#імпортуємо з модуля matrices функції Matrix, eye, zeros, ones, diag

from sympy.matrices import Matrix, eye, zeros, ones, diag
init_printing(pretty_print=True, use_latex=False)

In [56]:
#задамо матрицю з векторів
Matrix([[1,0,0], [1,1,1]])

⎡1  0  0⎤
⎢       ⎥
⎣1  1  1⎦

In [57]:
#задамо розмірність матриці та список елементів матриці
Matrix(2, 3, [1, 0, 0, 1, 1, 1])

⎡1  0  0⎤
⎢       ⎥
⎣1  1  1⎦

In [58]:
#задамо одиничну матрицю розмірності 3Х3
eye(3,3)

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦

In [59]:
#задамо матрицю з нулів розмірності 3х2
zeros(3, 2)

⎡0  0⎤
⎢    ⎥
⎢0  0⎥
⎢    ⎥
⎣0  0⎦

In [60]:
#задамо квадратну матрицю з нулів порядку 3
zeros(3)

⎡0  0  0⎤
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎣0  0  0⎦

In [61]:
# задамо вектор-стовпчик з одиниць
ones(3,1) 

⎡1⎤
⎢ ⎥
⎢1⎥
⎢ ⎥
⎣1⎦

__Базові дії над матрицями__

In [62]:
# матриця розмірності 3х3 заповнена впорядкованим набором від 1 до 9
A = Matrix(3,3, range(1,10))
A

⎡1  2  3⎤
⎢       ⎥
⎢4  5  6⎥
⎢       ⎥
⎣7  8  9⎦

In [63]:
# елемент А23
A[1,2]

6

In [64]:
# 3-й стовпчик матриці А
A[0:, 2]

⎡3⎤
⎢ ⎥
⎢6⎥
⎢ ⎥
⎣9⎦

In [65]:
# частина матриці А без третього рядка та стовпця
A[0:2, 0:2]

⎡1  2⎤
⎢    ⎥
⎣4  5⎦

In [66]:
A[:, 2]

⎡3⎤
⎢ ⎥
⎢6⎥
⎢ ⎥
⎣9⎦

>Обчислити вираз: $2A - 3B +E$

In [67]:
A = Matrix([[0,3], [2, -8]])
A

⎡0  3 ⎤
⎢     ⎥
⎣2  -8⎦

In [68]:
B = Matrix([[4, -5], [8, -4]])
B

⎡4  -5⎤
⎢     ⎥
⎣8  -4⎦

In [69]:
E = eye(2)
E

⎡1  0⎤
⎢    ⎥
⎣0  1⎦

In [70]:
2*A

⎡0   6 ⎤
⎢      ⎥
⎣4  -16⎦

In [71]:
2*A - 3*B + E

⎡-11  21⎤
⎢       ⎥
⎣-20  -3⎦

> Обчислити добутки $A \times B$ та $B \times A$

In [72]:
A = Matrix([[5,-1]])
A

[5  -1]

In [73]:
B = Matrix([[4], [-8]])
B

⎡4 ⎤
⎢  ⎥
⎣-8⎦

In [74]:
A * B

[28]

In [75]:
B * A

⎡20   -4⎤
⎢       ⎥
⎣-40  8 ⎦

__УВАГА!__

На відміну від NumPy в SymPy команда `*` для матриць означає матричний добуток, а не поелементний

In [76]:
# визначник матриці функція det()
A = Matrix([[1, 2, 3], [3, 6, 2], [2, 0, 1]])
A, A.det()

⎛⎡1  2  3⎤     ⎞
⎜⎢       ⎥     ⎟
⎜⎢3  6  2⎥, -28⎟
⎜⎢       ⎥     ⎟
⎝⎣2  0  1⎦     ⎠

In [77]:
#обернена матриця функція inv()
A.inv()

⎡-3/14  1/14  1/2 ⎤
⎢                 ⎥
⎢-1/28  5/28  -1/4⎥
⎢                 ⎥
⎣ 3/7   -1/7   0  ⎦

In [78]:
# транспонування матриці функція transpose()
A.transpose()

⎡1  3  2⎤
⎢       ⎥
⎢2  6  0⎥
⎢       ⎥
⎣3  2  1⎦

##<center>__Самостійні завдання__</center>

> Скопіювати блок самостійних завдань в окремий файл ***LastName_CP2.ipynb***

> Інсталюйте необхідні пакети бібліотек Python

In [79]:
import numpy as np

### Завдання №1

1. Задати матрицю $A$ розмірності $4х5$ з цілих чисел. 
2. Вивести другий рядок матриці $A$.
3. Вивести третій стовпчик матриці $A$. 
4. Вивести елемент $a_{13}$
5. Транспонувати матрицю $A$
5. Вивести матрицю $B$, яка є частиною матриці $A$ з перших трьох рядків та стовпців.
6. Знайти визначник матриці $B$

In [80]:
# задаємо матрицю A
A = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

# виводимо другий рядок матриці A
print("Другий рядок матриці A:")
print(A[1, :])

# виводимо третій стовпчик матриці A
print("Третій стовпчик матриці A:")
print(A[:, 2])

# виводимо елемент a13
print("Елемент a13:")
print(A[0, 2])

# транспонуємо матрицю A
A_T = A.T
print("Транспонована матриця A:")
print(A_T)

# виводимо матрицю B, що складається з перших трьох рядків та стовпців матриці A
B = A[:3, :3]
print("Матриця B:")
print(B)

# знаходимо визначник матриці B
det_B = np.linalg.det(B)
print("Визначник матриці B:")
print(det_B)

Другий рядок матриці A:
[ 6  7  8  9 10]
Третій стовпчик матриці A:
[ 3  8 13 18]
Елемент a13:
3
Транспонована матриця A:
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
Матриця B:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
Визначник матриці B:
0.0


### Завдання №2

1. Задати матрицю $A$ розмірності $2х3$ з цілих чисел. 
2. Задати матрицю $B$ розмірності $3х2$ з цілих чисел
3. Обчислити добуток $AB$ та $BA$ 
4. Перемножити поелементно $AB^T$ $BA^T$
5. Обчислити вираз $(2A-3B^T)N$, де $N$ - квадратна матриця з одиниць, порядку, що дозволяє оперцію множення


In [81]:
# задаємо матрицю A
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# задаємо матрицю B
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# обчислюємо добуток AB
AB = np.dot(A, B)
print("Добуток AB:")
print(AB)

# обчислюємо добуток BA
BA = np.dot(B, A)
print("Добуток BA:")
print(BA)

# обчислюємо поелементний добуток ABT та BAT
ABT = np.multiply(A, B.T)
BAT = np.multiply(B, A.T)
print("Поелементний добуток ABT та BAT:")
print(ABT)
print(BAT)

# обчислюємо вираз (2A - 3BT)N
N = np.eye(3)
result = np.dot(2*A - 3*B.T, N)
print("Вираз (2A - 3BT)N:")
print(result)

Добуток AB:
[[ 58  64]
 [139 154]]
Добуток BA:
[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]
Поелементний добуток ABT та BAT:
[[ 7 18 33]
 [32 50 72]]
[[ 7 32]
 [18 50]
 [33 72]]
Вираз (2A - 3BT)N:
[[-19. -23. -27.]
 [-16. -20. -24.]]


### Завдання №3

Знайти розв'язок системи лінійних рівнянь
$$\begin{cases}
   2x_1+5x_2-4x_3=-3\\
   3x_1-8x_2+3x_3=11\\
   5x_1+6x_2-4x_3=-1
 \end{cases} $$. 
1. Перевірити за теоремою Кронекера-Капеллі, що система має єдиний розв'язок
1. За допомогою вбудованої функції з бібліотеки Python
2. За допомогою матричного методу
3. За допомогою методу Крамера 
4. Зробити перевірку, що знайдений розв'язок задовільняє систему
5. Знайти власні числа та власні вектори матриці А


In [82]:
# 1
A = np.array([[2, 5, -4], [3, -8, 3], [5, 6, -4]])
b = np.array([-3, 11, -1])

# Розширена матриця системи
Ab = np.column_stack((A, b))

# Ранг матриці A та ранг розширеної матриці Ab
rank_A = np.linalg.matrix_rank(A)
rank_Ab = np.linalg.matrix_rank(Ab)

if rank_A == rank_Ab == 3:
    print("Система має єдиний розв'язок")
else:
    print("Система не має єдиного розв'язку")

Система має єдиний розв'язок


In [83]:
# 2
x = np.linalg.solve(A, b)

print("Розв'язок системи лінійних рівнянь:", x)

Розв'язок системи лінійних рівнянь: [ 1.00000000e+00 -1.00000000e+00  7.46584759e-16]


In [84]:
# 3
x = np.dot(np.linalg.inv(A), b)
print("Розв'язок системи за допомогою матричного методу:", x)

Розв'язок системи за допомогою матричного методу: [ 1.00000000e+00 -1.00000000e+00  2.77555756e-16]


In [85]:
# 4
D = np.linalg.det(A)
if D == 0:
    print("Система рівнянь має нескінченну кількість розв'язків")
else:
    D1 = np.array([[b[0], A[0, 1], A[0, 2]], [b[1], A[1, 1], A[1, 2]], [b[2], A[2, 1], A[2, 2]]])
    D2 = np.array([[A[0, 0], b[0], A[0, 2]], [A[1, 0], b[1], A[1, 2]], [A[2, 0], b[2], A[2, 2]]])
    D3 = np.array([[A[0, 0], A[0, 1], b[0]], [A[1, 0], A[1, 1], b[1]], [A[2, 0], A[2, 1], b[2]]])
x1 = np.linalg.det(D1) / D
x2 = np.linalg.det(D2) / D
x3 = np.linalg.det(D3) / D

print("Метод крамара:", [x1, x2, x3])

Метод крамара: [1.0, -1.0, 7.4658475858851e-16]


In [86]:
#5
from numpy.linalg import linalg

result = A@[x1, x2,x3]
print("підставимо у наше рівняння отримані розв'язки і виходить:", result)
if(linalg.norm(result - b) < 1e-6): print("відповідь підійшла")

підставимо у наше рівняння отримані розв'язки і виходить: [-3. 11. -1.]
відповідь підійшла


In [87]:
#6
eigvals, eigvecs = np.linalg.eig(A)
print("Власні числа матриці А:", eigvals)
print("Власні вектори матриці А:", eigvecs)

Власні числа матриці А: [  0.51083043+2.44937783j   0.51083043-2.44937783j
 -11.02166086+0.j        ]
Власні вектори матриці А: [[-0.26574728-0.36956459j -0.26574728+0.36956459j  0.43184973+0.j        ]
 [-0.38275228-0.02011423j -0.38275228+0.02011423j -0.81414291+0.j        ]
 [-0.80367687+0.j         -0.80367687-0.j          0.38817153+0.j        ]]


### Завдання №4

Знайти границі функції:

1. $$\lim_{x\to\infty} \frac{2x^3+3x^2-7}{4x^2+5x-8}$$

2. $$\lim_{x\to\infty} \left(\frac{x+4}{x+8}\right)^{-3x}$$
3. $$\lim_{x\to 0} \frac{x^2+x-12}{\sqrt{x-2}-\sqrt{4-x}}$$
4. $$\lim_{x\to 2} \frac{x^2-5x+6}{x^2-12x+20}$$
5. $$\lim_{x\to 0} \frac{\tan(3x)-\sin(3x)}{2x^2}$$






In [88]:
import sympy as sp
from sympy.abc import x

from sympy.calculus.util import *
f = (2*x**3 + 3*x**2 - 7) / (4*x**2 + 5*x - 8)
limit(f, x, oo)

∞

In [89]:
limit(((x+4)/(x+8))**(-3*x), x, oo)

 12
ℯ  

In [90]:
f = (x**2 + x -12)/(sp.sqrt(x-2) - sp.sqrt(4-x))
limit(f, x, 0)

   -12   
─────────
-2 + √2⋅ⅈ

In [91]:
f = (x**2 -5*x +6)/(x**2 - 12*x + 20)
limit(f, x, 2)

1/8

In [92]:
f = (sp.tan(3*x) - sp.sin(3*x))/(2*x**2)
limit(f, x, 0)

0

### Завдання №5

Знайти похідну функцій

1. $$y=x\sin^3(3x)$$
1. $$y=\ln(x^4-\cos^2(x))$$
2. $$y=x^2\tan(2x)+e^{6x}$$
3. Знайти похідні до 3-го порядку включно
$$y=x^2-5\sin(4x)+3^{2x} $$



In [93]:
y = x*sp.sin(3*x)**3

dy_dx = sp.diff(y, x)

print(dy_dx)

9*x*sin(3*x)**2*cos(3*x) + sin(3*x)**3


In [95]:
y = sp.ln(x**4 - sp.cos(x)**2)

dy_dx = sp.diff(y, x)

print(dy_dx)

(4*x**3 + 2*sin(x)*cos(x))/(x**4 - cos(x)**2)


In [96]:
y = x**2 * sp.tan(2*x) + sp.exp(6*x)

dy_dx = sp.diff(y, x)

print(dy_dx)

x**2*(2*tan(2*x)**2 + 2) + 2*x*tan(2*x) + 6*exp(6*x)


In [97]:
y = x**2 - 5* sp.sin(4*x) + 3**(2*x)

dy_dx = sp.diff(y, x)

print(dy_dx)

2*3**(2*x)*log(3) + 2*x - 20*cos(4*x)


### Завдання №6

Знайти невизначений інеграл

1. $$\int \frac{2-x}{4x^2+16x-12} \,dx$$
1. $$\int \frac{7x-1}{\sqrt{2x^2-x+5}} \,dx$$
3. $$\int \frac{\ln(x)}{x^3} \,dx$$
4. $$\int \frac{x\arccos(2x)}{\sqrt{1-4x^2}} \,dx$$

Обчислити визначений інтеграл

1. $$\int_{1}^{2} 3(x-1)^2 \,dx$$
2. $$\int_{0}^{\pi/2} \sin^3(x) \,dx$$
3. $$\int_{1}^{+\infty} \frac{1}{x^2+4x+13} \,dx$$
4. $$\int_{1}^{+\infty} \frac{2+\sin(x)}{\sqrt{x}},dx$$


Невизначений

In [98]:
f = (2 - x) / (4 * x**2 + 16 * x - 12)
F = sp.integrate(f, x)
print(F)

-(1/8 + sqrt(7)/14)*log(x + 2 + sqrt(7)) - (1/8 - sqrt(7)/14)*log(x - sqrt(7) + 2)


In [102]:
f = (7*x-1)/(sp.sqrt(2*x**2 - x + 5))
F = sp.integrate(f, x)
print(F)

Integral((7*x - 1)/sqrt(2*x**2 - x + 5), x)


In [100]:
f = (sp.ln(x))/x**3
F = sp.integrate(f, x)
print(F)

-log(x)/(2*x**2) - 1/(4*x**2)


In [104]:
f = (x * sp.acos(2*x))/(sp.sqrt(1-4*x**2))
F = sp.integrate(f, x)
print(F)

-x/2 - sqrt(1 - 4*x**2)*acos(2*x)/4


Визначений

In [110]:
f = 3 * (x - 1) ** 2
a = 1
b = 2
result = sp.integrate(f, (x, a, b))
print(result)

1


In [111]:
f = sp.sin(x)**3
a = 0
b = sp.pi / 2 
result = sp.integrate(f, (x, a, b))
print(result)

2/3


In [119]:
f = (2 + sp.sin(x)**2)/(sp.sqrt(x))
a = 1
b = oo
result = sp.integrate(f, (x, a, b))
print(result)

oo
