<a href="https://colab.research.google.com/github/trilgar/IAD2023/blob/main/%D0%97%D0%B0%D1%80%D0%B8%D1%86%D1%8C%D0%BA%D0%B8%D0%B9_CP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<center><font size="6"><b>Комп'ютерний практикум 2.

Python для математичних обчислень</b></font></center>

##<center>__Самостійні завдання__</center>

> Скопіювати блок самостійних завдань в окремий файл ***LastName_CP2.ipynb***

> Інсталюйте необхідні пакети бібліотек Python

In [79]:
import numpy as np

### Завдання №1

1. Задати матрицю $A$ розмірності $4х5$ з цілих чисел. 
2. Вивести другий рядок матриці $A$.
3. Вивести третій стовпчик матриці $A$. 
4. Вивести елемент $a_{13}$
5. Транспонувати матрицю $A$
5. Вивести матрицю $B$, яка є частиною матриці $A$ з перших трьох рядків та стовпців.
6. Знайти визначник матриці $B$

In [80]:
# задаємо матрицю A
A = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])

# виводимо другий рядок матриці A
print("Другий рядок матриці A:")
print(A[1, :])

# виводимо третій стовпчик матриці A
print("Третій стовпчик матриці A:")
print(A[:, 2])

# виводимо елемент a13
print("Елемент a13:")
print(A[0, 2])

# транспонуємо матрицю A
A_T = A.T
print("Транспонована матриця A:")
print(A_T)

# виводимо матрицю B, що складається з перших трьох рядків та стовпців матриці A
B = A[:3, :3]
print("Матриця B:")
print(B)

# знаходимо визначник матриці B
det_B = np.linalg.det(B)
print("Визначник матриці B:")
print(det_B)

Другий рядок матриці A:
[ 6  7  8  9 10]
Третій стовпчик матриці A:
[ 3  8 13 18]
Елемент a13:
3
Транспонована матриця A:
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
Матриця B:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
Визначник матриці B:
0.0


### Завдання №2

1. Задати матрицю $A$ розмірності $2х3$ з цілих чисел. 
2. Задати матрицю $B$ розмірності $3х2$ з цілих чисел
3. Обчислити добуток $AB$ та $BA$ 
4. Перемножити поелементно $AB^T$ $BA^T$
5. Обчислити вираз $(2A-3B^T)N$, де $N$ - квадратна матриця з одиниць, порядку, що дозволяє оперцію множення


In [81]:
# задаємо матрицю A
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# задаємо матрицю B
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# обчислюємо добуток AB
AB = np.dot(A, B)
print("Добуток AB:")
print(AB)

# обчислюємо добуток BA
BA = np.dot(B, A)
print("Добуток BA:")
print(BA)

# обчислюємо поелементний добуток ABT та BAT
ABT = np.multiply(A, B.T)
BAT = np.multiply(B, A.T)
print("Поелементний добуток ABT та BAT:")
print(ABT)
print(BAT)

# обчислюємо вираз (2A - 3BT)N
N = np.eye(3)
result = np.dot(2*A - 3*B.T, N)
print("Вираз (2A - 3BT)N:")
print(result)

Добуток AB:
[[ 58  64]
 [139 154]]
Добуток BA:
[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]
Поелементний добуток ABT та BAT:
[[ 7 18 33]
 [32 50 72]]
[[ 7 32]
 [18 50]
 [33 72]]
Вираз (2A - 3BT)N:
[[-19. -23. -27.]
 [-16. -20. -24.]]


### Завдання №3

Знайти розв'язок системи лінійних рівнянь
$$\begin{cases}
   2x_1+5x_2-4x_3=-3\\
   3x_1-8x_2+3x_3=11\\
   5x_1+6x_2-4x_3=-1
 \end{cases} $$. 
1. Перевірити за теоремою Кронекера-Капеллі, що система має єдиний розв'язок
1. За допомогою вбудованої функції з бібліотеки Python
2. За допомогою матричного методу
3. За допомогою методу Крамера 
4. Зробити перевірку, що знайдений розв'язок задовільняє систему
5. Знайти власні числа та власні вектори матриці А


In [82]:
# 1
A = np.array([[2, 5, -4], [3, -8, 3], [5, 6, -4]])
b = np.array([-3, 11, -1])

# Розширена матриця системи
Ab = np.column_stack((A, b))

# Ранг матриці A та ранг розширеної матриці Ab
rank_A = np.linalg.matrix_rank(A)
rank_Ab = np.linalg.matrix_rank(Ab)

if rank_A == rank_Ab == 3:
    print("Система має єдиний розв'язок")
else:
    print("Система не має єдиного розв'язку")

Система має єдиний розв'язок


In [83]:
# 2
x = np.linalg.solve(A, b)

print("Розв'язок системи лінійних рівнянь:", x)

Розв'язок системи лінійних рівнянь: [ 1.00000000e+00 -1.00000000e+00  7.46584759e-16]


In [84]:
# 3
x = np.dot(np.linalg.inv(A), b)
print("Розв'язок системи за допомогою матричного методу:", x)

Розв'язок системи за допомогою матричного методу: [ 1.00000000e+00 -1.00000000e+00  2.77555756e-16]


In [85]:
# 4
D = np.linalg.det(A)
if D == 0:
    print("Система рівнянь має нескінченну кількість розв'язків")
else:
    D1 = np.array([[b[0], A[0, 1], A[0, 2]], [b[1], A[1, 1], A[1, 2]], [b[2], A[2, 1], A[2, 2]]])
    D2 = np.array([[A[0, 0], b[0], A[0, 2]], [A[1, 0], b[1], A[1, 2]], [A[2, 0], b[2], A[2, 2]]])
    D3 = np.array([[A[0, 0], A[0, 1], b[0]], [A[1, 0], A[1, 1], b[1]], [A[2, 0], A[2, 1], b[2]]])
x1 = np.linalg.det(D1) / D
x2 = np.linalg.det(D2) / D
x3 = np.linalg.det(D3) / D

print("Метод крамара:", [x1, x2, x3])

Метод крамара: [1.0, -1.0, 7.4658475858851e-16]


In [86]:
#5
from numpy.linalg import linalg

result = A@[x1, x2,x3]
print("підставимо у наше рівняння отримані розв'язки і виходить:", result)
if(linalg.norm(result - b) < 1e-6): print("відповідь підійшла")

підставимо у наше рівняння отримані розв'язки і виходить: [-3. 11. -1.]
відповідь підійшла


In [87]:
#6
eigvals, eigvecs = np.linalg.eig(A)
print("Власні числа матриці А:", eigvals)
print("Власні вектори матриці А:", eigvecs)

Власні числа матриці А: [  0.51083043+2.44937783j   0.51083043-2.44937783j
 -11.02166086+0.j        ]
Власні вектори матриці А: [[-0.26574728-0.36956459j -0.26574728+0.36956459j  0.43184973+0.j        ]
 [-0.38275228-0.02011423j -0.38275228+0.02011423j -0.81414291+0.j        ]
 [-0.80367687+0.j         -0.80367687-0.j          0.38817153+0.j        ]]


### Завдання №4

Знайти границі функції:

1. $$\lim_{x\to\infty} \frac{2x^3+3x^2-7}{4x^2+5x-8}$$

2. $$\lim_{x\to\infty} \left(\frac{x+4}{x+8}\right)^{-3x}$$
3. $$\lim_{x\to 0} \frac{x^2+x-12}{\sqrt{x-2}-\sqrt{4-x}}$$
4. $$\lim_{x\to 2} \frac{x^2-5x+6}{x^2-12x+20}$$
5. $$\lim_{x\to 0} \frac{\tan(3x)-\sin(3x)}{2x^2}$$






In [88]:
import sympy as sp
from sympy.abc import x

from sympy.calculus.util import *
f = (2*x**3 + 3*x**2 - 7) / (4*x**2 + 5*x - 8)
limit(f, x, oo)

∞

In [89]:
limit(((x+4)/(x+8))**(-3*x), x, oo)

 12
ℯ  

In [90]:
f = (x**2 + x -12)/(sp.sqrt(x-2) - sp.sqrt(4-x))
limit(f, x, 0)

   -12   
─────────
-2 + √2⋅ⅈ

In [91]:
f = (x**2 -5*x +6)/(x**2 - 12*x + 20)
limit(f, x, 2)

1/8

In [92]:
f = (sp.tan(3*x) - sp.sin(3*x))/(2*x**2)
limit(f, x, 0)

0

### Завдання №5

Знайти похідну функцій

1. $$y=x\sin^3(3x)$$
1. $$y=\ln(x^4-\cos^2(x))$$
2. $$y=x^2\tan(2x)+e^{6x}$$
3. Знайти похідні до 3-го порядку включно
$$y=x^2-5\sin(4x)+3^{2x} $$



In [93]:
y = x*sp.sin(3*x)**3

dy_dx = sp.diff(y, x)

print(dy_dx)

9*x*sin(3*x)**2*cos(3*x) + sin(3*x)**3


In [95]:
y = sp.ln(x**4 - sp.cos(x)**2)

dy_dx = sp.diff(y, x)

print(dy_dx)

(4*x**3 + 2*sin(x)*cos(x))/(x**4 - cos(x)**2)


In [96]:
y = x**2 * sp.tan(2*x) + sp.exp(6*x)

dy_dx = sp.diff(y, x)

print(dy_dx)

x**2*(2*tan(2*x)**2 + 2) + 2*x*tan(2*x) + 6*exp(6*x)


In [97]:
y = x**2 - 5* sp.sin(4*x) + 3**(2*x)

dy_dx = sp.diff(y, x)

print(dy_dx)

2*3**(2*x)*log(3) + 2*x - 20*cos(4*x)


### Завдання №6

Знайти невизначений інеграл

1. $$\int \frac{2-x}{4x^2+16x-12} \,dx$$
1. $$\int \frac{7x-1}{\sqrt{2x^2-x+5}} \,dx$$
3. $$\int \frac{\ln(x)}{x^3} \,dx$$
4. $$\int \frac{x\arccos(2x)}{\sqrt{1-4x^2}} \,dx$$

Обчислити визначений інтеграл

1. $$\int_{1}^{2} 3(x-1)^2 \,dx$$
2. $$\int_{0}^{\pi/2} \sin^3(x) \,dx$$
3. $$\int_{1}^{+\infty} \frac{1}{x^2+4x+13} \,dx$$
4. $$\int_{1}^{+\infty} \frac{2+\sin(x)}{\sqrt{x}},dx$$


Невизначений

In [98]:
f = (2 - x) / (4 * x**2 + 16 * x - 12)
F = sp.integrate(f, x)
print(F)

-(1/8 + sqrt(7)/14)*log(x + 2 + sqrt(7)) - (1/8 - sqrt(7)/14)*log(x - sqrt(7) + 2)


In [102]:
f = (7*x-1)/(sp.sqrt(2*x**2 - x + 5))
F = sp.integrate(f, x)
print(F)

Integral((7*x - 1)/sqrt(2*x**2 - x + 5), x)


In [100]:
f = (sp.ln(x))/x**3
F = sp.integrate(f, x)
print(F)

-log(x)/(2*x**2) - 1/(4*x**2)


In [104]:
f = (x * sp.acos(2*x))/(sp.sqrt(1-4*x**2))
F = sp.integrate(f, x)
print(F)

-x/2 - sqrt(1 - 4*x**2)*acos(2*x)/4


Визначений

In [110]:
f = 3 * (x - 1) ** 2
a = 1
b = 2
result = sp.integrate(f, (x, a, b))
print(result)

1


In [111]:
f = sp.sin(x)**3
a = 0
b = sp.pi / 2 
result = sp.integrate(f, (x, a, b))
print(result)

2/3


In [119]:
f = (2 + sp.sin(x)**2)/(sp.sqrt(x))
a = 1
b = oo
result = sp.integrate(f, (x, a, b))
print(result)

oo
